apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dm-api-3 # the name display in argocd UI
  namespace: argocd  #what's this. why I can't specify other namespace here. otherwise, it failed to display child project
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helloworld
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: dm-api-3
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy: # added by ken
    automated:
        prune: true
        allowEmpty: true
        selfHeal: true