apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dm-api-1 # the application name displayed in argocd UI
  namespace: argocd  #argocd namespace
  #finalizers:  commented by ken, to fix delete stuck
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helloworld
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: dm-api-1
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  # syncPolicy: # added by ken, to fix deletion stuck
  #   automated:
  #       prune: true
  #       allowEmpty: true
  #       selfHeal: true
  syncPolicy:
    syncOptions:
    - PrunePropagationPolicy=foreground